export const ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  CONVERSATION_NOT_FOUND: "CONVERSATION_NOT_FOUND",
  API_KEY_NOT_CONFIGURED: "API_KEY_NOT_CONFIGURED",
  INVALID_API_KEY: "INVALID_API_KEY",
  INVALID_REQUEST: "INVALID_REQUEST",
  MISSING_FIELDS: "MISSING_FIELDS",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  ENCRYPTION_ERROR: "ENCRYPTION_ERROR",
  UPLOAD_ERROR: "UPLOAD_ERROR",
  CACHE_ERROR: "CACHE_ERROR",
  MODEL_REQUIRED: "MODEL_REQUIRED",
} as const;

export const API_ERROR_MESSAGES = {
  [ERROR_CODES.UNAUTHORIZED]: "Unauthorized",
  [ERROR_CODES.CONVERSATION_NOT_FOUND]: "Conversation not found",
  [ERROR_CODES.API_KEY_NOT_CONFIGURED]: "API key not configured",
  [ERROR_CODES.INVALID_API_KEY]: "Invalid API key",
  [ERROR_CODES.MODEL_REQUIRED]: "Model is required and must be a string",
  INVALID_API_KEY_FORMAT: "Invalid OpenAI API key format",
  INVALID_CONVERSATION_ID: "Invalid conversation ID format",
  MISSING_MODEL_MESSAGES: "Missing required fields: model, messages",
  MISSING_ROLE_CONTENT: "Role and content are required",
  INVALID_ROLE: "Invalid role. Must be USER, ASSISTANT, or SYSTEM",
  TITLE_REQUIRED: "Title is required",
  TITLE_TOO_LONG: "Title is too long",
  CONTENT_TOO_LONG: "Content is too long",
  MESSAGE_TOO_LONG: "Message is too long",
  TOO_MANY_MESSAGES: "Too many messages",
  INVALID_REQUEST_BODY: "Invalid request body",
  PAYLOAD_TOO_LARGE: "Request payload is too large",
  FAILED_FETCH_CONVERSATIONS: "Failed to fetch conversations",
  FAILED_CREATE_CONVERSATION: "Failed to create conversation",
  FAILED_DELETE_CONVERSATION: "Failed to delete conversation",
  FAILED_DELETE_CONVERSATIONS: "Failed to delete conversations",
  INVALID_CONVERSATION_IDS: "Invalid conversation IDs provided",
  FAILED_FETCH_CONVERSATION: "Failed to fetch conversation",
  FAILED_UPDATE_CONVERSATION: "Failed to update conversation",
  FAILED_CREATE_MESSAGE: "Failed to create message",
  FAILED_SAVE_API_KEY: "Failed to save API key",
  FAILED_RETRIEVE_API_KEY: "Failed to retrieve API key status",
  FAILED_DELETE_API_KEY: "Failed to delete API key",
  CACHE_CHECK_FAILED: "Cache check failed",
  CACHE_SAVE_FAILED: "Cache save failed",
  MEMORY_FETCH_FAILED: "Failed to fetch memories",
  MEMORY_ADD_FAILED: "Failed to add memory",
  MEMORY_DELETE_FAILED: "Failed to delete memory",
  MEMORY_DELETE_NOT_FOUND: "Memory not found or could not be deleted",
  MEMORY_UPDATE_FAILED: "Failed to update memory",
  MEMORY_UPDATE_NOT_FOUND: "Memory not found or could not be updated",
  MEMORY_SEARCH_FAILED: "Failed to search memories",
  MEMORY_EXTRACT_FAILED: "Failed to extract memories",
  OG_IMAGE_GENERATION_FAILED: "Failed to generate image",
  INTERNAL_SERVER_ERROR: "Internal server error",
  NO_RESPONSE_STREAM: "No response stream",
  OPENAI_RATE_LIMIT: "Rate limit exceeded. Please try again later",
  OPENAI_INSUFFICIENT_QUOTA: "Insufficient quota. Please check your OpenAI account billing",
  OPENAI_INVALID_API_KEY: "Invalid OpenAI API key. Please update your API key",
  OPENAI_MODEL_NOT_FOUND: "Model not found or not accessible with your API key",
  OPENAI_CONTEXT_LENGTH_EXCEEDED: "Message context is too long for this model",
  PDF_GENERATION_FAILED: "Failed to generate PDF",
  ATTACHMENT_NOT_FOUND: "Attachment not found",
  ATTACHMENT_UNAUTHORIZED: "Unauthorized access to attachment",
  RAG_MISSING_ENV_VARS: "Missing required environment variables",
  RAG_INVALID_EMBEDDING_DIMENSIONS: "EMBEDDING_DIMENSIONS must be a positive integer",
  RERANK_API_ERROR: "Reranking API error",
  RERANK_MISSING_API_KEY: "Cohere API key not configured for reranking",
} as const;

export const TOAST_ERROR_MESSAGES = {
  AUTH: {
    REQUIRED: "Authentication Required",
    REQUIRED_DESCRIPTION: "Please login to start chatting",
    FAILED_SIGN_IN: "Failed to sign in",
    FAILED_SIGN_IN_DESCRIPTION: "Please try again later",
    FAILED_LOGOUT: "Failed to logout",
    FAILED_LOGOUT_DESCRIPTION: "Please try again",
  },
  API_KEY: {
    REQUIRED: "API Key Required",
    REQUIRED_DESCRIPTION: "Please configure your OpenAI API key first",
    INVALID_FORMAT: "Invalid API key format",
    INVALID_FORMAT_DESCRIPTION: "Valid formats: sk-..., sk-proj-..., or sk-svcacct-...",
    ENTER_KEY: "Please enter your OpenAI API key",
    FAILED_SAVE: "Failed to save API key",
    FAILED_CLEAR: "Failed to clear settings",
  },
  MODEL: {
    NOT_SELECTED: "Model not selected",
    FAILED_SAVE: "Failed to save model preference",
  },
  CHAT: {
    FAILED_SEND: "Failed to send message",
  },
  UPLOAD: {
    FAILED: "Upload failed",
    TOO_MANY_FILES: "Too many files",
    MAX_REACHED: "Maximum files reached",
    UNSUPPORTED_FORMAT: "Unsupported image format",
  },
  CONVERSATION: {
    FAILED_CREATE: "Failed to create conversation",
    FAILED_DELETE: "Failed to delete conversation",
    FAILED_DELETE_MULTIPLE: "Failed to delete conversations",
    FAILED_RENAME: "Failed to rename conversation",
    FAILED_SHARE: "Failed to update sharing settings",
  },
  CACHE: {
    FAILED_CHECK: "Cache check failed",
    FAILED_SAVE: "Failed to save to cache",
  },
  MEMORY: {
    FAILED_FETCH: "Failed to fetch memories",
    FAILED_ADD: "Failed to add memory",
    FAILED_DELETE: "Failed to delete memory",
    FAILED_SEARCH: "Failed to search memories",
    FAILED_EXTRACT: "Failed to extract memories",
  },
  CONTEXT: {
    LIMIT_REACHED: "Context limit reached",
    LIMIT_REACHED_DESCRIPTION: "Start a new chat to continue",
  },
  TOOLS: {
    ACTIVATED: "Tool activated",
    DEACTIVATED: "Tool deactivated",
    AUTH_REQUIRED_DESCRIPTION: "Please sign in to use tools",
  },
  DEEP_RESEARCH_UI: {
    DEACTIVATED: "Deep Research deactivated",
    LIMIT_REACHED: "Deep Research limit reached",
    LIMIT_REACHED_DESCRIPTION: "You have used all your deep research requests for this month. Your message will be sent with standard processing.",
    UNAVAILABLE: "Deep Research unavailable",
    MONTHLY_LIMIT_DESCRIPTION: (limit: number, resetDate: string) =>
      `You have used all ${limit} deep research requests for this month. Resets on ${resetDate}.`,
  },
  MEMORY_UI: {
    ENABLED: "Memory enabled",
    DISABLED: "Memory disabled",
    AUTH_REQUIRED_DESCRIPTION: "Please sign in to use memory features",
  },
} as const;

export const ENCRYPTION_ERRORS = {
  KEY_NOT_SET: "ENCRYPTION_KEY environment variable is not set",
  FAILED_ENCRYPT: "Failed to encrypt API key",
  INVALID_FORMAT: "Invalid encrypted data format",
  FAILED_DECRYPT: "Failed to decrypt API key",
} as const;

export const HOOK_ERROR_MESSAGES = {
  FAILED_FETCH_API_KEY: "Failed to fetch API key status",
  FAILED_DELETE_API_KEY: "Failed to delete API key",
  FAILED_FETCH_CONVERSATIONS: "Failed to fetch conversations",
  FAILED_CREATE_CONVERSATION: "Failed to create conversation",
  FAILED_DELETE_CONVERSATION: "Failed to delete conversation",
  FAILED_DELETE_CONVERSATIONS: "Failed to delete conversations",
  FAILED_UPDATE_CONVERSATION: "Failed to update conversation",
  FAILED_FETCH_CONVERSATION: "Failed to fetch conversation",
  FAILED_CACHE_CHECK: "Cache check failed",
  FAILED_SAVE_CACHE: "Failed to save to cache",
  FAILED_MEMORY_FETCH: "Failed to fetch memories",
  FAILED_MEMORY_SEARCH: "Failed to search memories",
  UNKNOWN_ERROR: "Unknown error",
  UNKNOWN_ERROR_OCCURRED: "Unknown error occurred",
} as const;

export const TOOL_ERROR_MESSAGES = {
  WEB_SEARCH: {
    NOT_CONFIGURED: 'Web search is not configured. Please set TAVILY_API_KEY environment variable.',
    NO_RESULTS: (query: string) => `No results found for "${query}". Try rephrasing your search query.`,
    SEARCH_FAILED: (error: string) => `Failed to perform web search: ${error}`,
    ABORTED: 'Search was aborted, please try again later.',
    FAILED_FALLBACK: 'Search failed, continuing without web results...',
  },
  YOUTUBE: {
    NO_URLS_DETECTED: 'YouTube tool is active but no YouTube URLs detected in your message. Please provide YouTube video links.',
    INVALID_URL: (url: string) => `Invalid YouTube URL: ${url}`,
    NO_TRANSCRIPT: (videoId: string) => `No transcript available for video ${videoId}. The video may not have captions enabled.`,
    PRIVATE_VIDEO: 'This video is private or age-restricted and cannot be accessed.',
    RATE_LIMIT: 'YouTube rate limit reached. Please try again later.',
    NETWORK_ERROR: (error: string) => `Network error while fetching YouTube data: ${error}`,
    TOOL_FAILED: (error: string) => `YouTube tool failed: ${error}`,
    BATCH_LIMIT_EXCEEDED: 'Maximum 5 videos allowed per request.',
    ABORTED: 'YouTube analysis was aborted, please try again later.',
    FAILED_FALLBACK: 'YouTube processing failed, continuing without video data...',
  },
  DEEP_RESEARCH: {
    ABORTED: 'Research was aborted, please try again later.',
    FAILED: 'Research failed',
    FAILED_DETAILED: 'Deep research encountered an error and could not be completed. Please try again or rephrase your query.',
    FAILED_FALLBACK: 'I encountered an issue while conducting deep research. Let me provide an answer based on my knowledge instead.\n\n',
    EXECUTION_ERROR: '⚠️ Unable to complete deep research. Let me answer based on my knowledge instead.\n\n',
    RATE_LIMIT: '⚠️ **Deep Research Limit Reached**\n\nYou have used all your deep research requests for this month.\n\n📅 Your limit will reset at the beginning of next month.\n\nI\'ll answer your question using standard processing instead.\n\n---\n\n',
    TECHNICAL_ERROR: '⚠️ Unable to perform deep research at this time due to a technical issue. Let me answer based on my knowledge instead.\n\n',
    AUTH_REQUIRED: '⚠️ Authentication error: Unable to verify your identity for deep research. Please refresh and try again.\n\n',
  },
  GOOGLE_SUITE: {
    ABORTED: 'Google Suite operation was aborted, please try again later.',
    OPERATION_ABORTED_BY_USER: 'Operation aborted by user',
    FAILED_FALLBACK: 'Google Suite operation failed, continuing without Gmail data...',
    AUTH_REQUIRED: '⚠️ Authentication required for Google Suite access.',
    AUTH_REQUIRED_MENU: 'Google account not authorized. Please sign in with Google via the Tools menu.',
    AUTH_REVOKED: 'Error: Your Google Workspace authorization has been revoked or expired. Please sign in with Google again via the Tools menu.',
    NO_RESPONSE: 'No response from AI',
    UNKNOWN_TOOL: (toolName: string) => `Unknown tool: ${toolName}`,
    INVALID_JSON_ARGS: 'Error: Invalid JSON arguments',
    INVALID_MESSAGE_STRUCTURE: (index: number) => `Invalid message structure: tool message at index ${index} without preceding tool_calls`,
    MULTIPLE_ERRORS: 'Multiple consecutive errors occurred. Please check your request and try again.',
    UNEXPECTED_ERROR: 'An unexpected error occurred while accessing Google Workspace.',
    MAX_ITERATIONS_REACHED: 'Task execution reached maximum iterations. Some steps may be incomplete.',
    MISSING_OAUTH_CREDENTIALS: 'Missing Google OAuth credentials in environment variables',
    NOT_AUTHORIZED_MENU: 'Google Workspace access not authorized. Please sign in with Google via the Tools menu.',
    INVALID_START_TIME: (time: string) => `Invalid startTime format: "${time}". Expected ISO 8601 format (e.g., "2025-01-20T10:00:00Z")`,
    INVALID_END_TIME: (time: string) => `Invalid endTime format: "${time}". Expected ISO 8601 format (e.g., "2025-01-20T11:00:00Z")`,
    END_TIME_BEFORE_START: (startTime: string, endTime: string) => `endTime (${endTime}) must be after startTime (${startTime})`,
    END_TIME_AFTER_START_REQUIRED: 'endTime must be after startTime',
  },
  GENERAL: {
    REQUEST_ABORTED: 'Request was aborted, please try again later.',
  },
} as const;

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  GONE: 410,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
