export const styles = {
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: "Helvetica",
    backgroundColor: "#ffffff",
    lineHeight: 1.5,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 12,
    borderBottomWidth: 1.5,
    borderBottomColor: "#000000",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 8,
    color: "#000000",
  },
  metadata: {
    fontSize: 8,
    color: "#666666",
    marginTop: 5,
    lineHeight: 1.4,
  },
  metadataRow: {
    flexDirection: "row",
    marginBottom: 2,
    flexWrap: "wrap",
  },
  metadataLabel: {
    fontWeight: "bold",
    width: 65,
    marginRight: 5,
  },
  metadataValue: {
    flex: 1,
  },
  messageContainer: {
    marginBottom: 16,
    padding: 10,
    backgroundColor: "#fafafa",
    borderRadius: 2,
    borderLeftWidth: 2,
    borderLeftColor: "#000000",
  },
  messageHeader: {
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: "#cccccc",
  },
  messageHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    flexWrap: "wrap",
  },
  messageRole: {
    fontSize: 9,
    fontWeight: "bold",
    color: "#000000",
    marginRight: 10,
  },
  messageTime: {
    fontSize: 7,
    color: "#666666",
  },
  messageContent: {
    fontSize: 9,
    lineHeight: 1.5,
    color: "#000000",
  },
  attachmentsSection: {
    marginTop: 8,
    paddingTop: 6,
    borderTopWidth: 0.5,
    borderTopColor: "#cccccc",
  },
  attachmentsTitle: {
    fontSize: 8,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 4,
  },
  attachment: {
    fontSize: 7,
    color: "#333333",
    marginBottom: 4,
    paddingLeft: 8,
    lineHeight: 1.4,
  },
  attachmentName: {
    fontWeight: "bold",
    color: "#000000",
  },
  attachmentUrl: {
    fontSize: 6,
    color: "#666666",
    marginTop: 1,
  },
  footer: {
    position: "absolute",
    bottom: 25,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 7,
    color: "#666666",
    borderTopWidth: 0.5,
    borderTopColor: "#cccccc",
    paddingTop: 8,
  },
} as const;
